### PR TITLE
Changes underscores to spaces in user-facing widget names

### PR DESCRIPTION
**Pull request by fbgrover**

### CODE REVIEW

**Comment by mattwkelly** [comment]
Cool, thanks. 

Btw, Is your editor doing something odd with new lines or something?  I see a bunch of empty lines removed/re-added (see https://github.com/mattwkelly/fb-hacks/pull/31/files).

**Comment by fbgrover** [comment]
Yeah using Textmate on a Mac, not sure what it's doing ;)

Sent from my iPhone

On May 4, 2012, at 6:52 PM, Matt Kelly
reply@reply.github.com
wrote:

**Comment by fbgrover** [comment]
So looks like I'm stripping whitespace on save in Textmate, since no-trailing-whitespace is an FB coding standard, i.e.  i have this set up: http://blogobaggins.com/2009/03/31/waging-war-on-whitespace.html

Looks like this is a wordpress coding standard too at:
http://codex.wordpress.org/WordPress_Coding_Standards#Remove_Trailing_Spaces

So we should probably all configure our editors this way.  Once everyone is set up with that in their editors, we can then strip trailing whitespace on all the files so our diffs look sane from then on.  What do you think?

http://codex.wordpress.org/WordPress_Coding_Standards

**Comment by fbgrover** [comment]
And/or could be related to this: http://help.github.com/line-endings/

Fun to be a github n00b ;)

**Comment by fbgrover** [comment]
Ok, so I believe it is definitely the whitespace thing - when I look at the diff here:

https://github.com/fbgrover/fb-hacks/commit/0298e287f762cf0dbc5c69c063a340e4b9d9489c

my diff has basically removed whitespace from those empty lines.  you can see the tabs/spaces that were there before by highlighting.

**Comment by mattwkelly** [comment]
Yeah, looks like you're right.  I toggled on cleaning up trailing whitespace and EOL markers on save--hopefully that fixes it.

**Pull request merged**
