### PR TITLE
general cleanup and suggestions

### PR DESCRIPTION
**Pull request by niallkennedy**
many changes to WordPress plugin files. more details in commits.

### CODE REVIEW

**Comment by mattwkelly** [comment]
Looking through this now.

**Comment by mattwkelly** [comment]
Great changes, thanks @niallkennedy.  Sorry for my newb WP mistakes/growing pains. :)

Out of curiosity, does WP have any functionality to automatically compress static files?

**Comment by niallkennedy** [comment]
WordPress uses YUI Compressor to minify JavaScript and CSS. http://yuilibrary.com/projects/yuicompressor/

Developers might set SCRIPT_DEBUG to true in their wp-config.php file to trigger loading uncompressed versions of the files. http://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG

**Comment by mattwkelly** [comment]
Got it, thanks

**Pull request merged**
