### PR TITLE
Fix for issue #169 - alt for wp_trim_words in ver < 3.3

### PR DESCRIPTION
**Pull request by colmdoyle**
Uses wp_trim_words for versions > 3.3, but just uses a php substr
function for earlier versions.

Since wp_trim_words counts words, not characters, I'm multiplying the
excerpt count by 4 to spoof this without adding a lot of word counting
logic.

### CODE REVIEW

**Comment by mattwkelly** [comment]
Makes sense. @colmdoyle , do you mind adding wp_trim_words back in, but wrap it in a function_exists if statement?

Also, add in a comment that once we drop support for anything under 3.3, we can drop the if statement.

**Comment by colmdoyle** [comment]
yep, sounds reasonable. I'll fire off a new pull request for it.

**Comment by mattwkelly** [comment]
@colmdoyle Note that you can just commit to your branch that you made the PR from and this issue will be auto-updated.  So then we don't lose history by opening another PR.

**Comment by colmdoyle** [comment]
ah, my bad.

**Pull request closed without merging**
