### PR TITLE
Function added for issue 146 regarding compatibility

### PR DESCRIPTION
**Pull request by rgharpuray**
This should have the function that adds the compatibility notification to the fb admin page.

### CODE REVIEW

**Comment by Otto42** [comment]
Two things of note:
1. Why is Hello Dolly in there? Testing?
2. Consider checking against the "PluginURI" value instead. This is more reliable than just checking against the name for matches. URIs should be more unique.

**Comment by rgharpuray** [comment]
yeah, the hello dolly was just for testing-- I'll be removing that really soon. Sounds good, I'll take a look at PluginURI instead of Name-

**Comment by rgharpuray** [comment]
Fixed. Using PluginURI now. Also removed Hello Dolly

**Comment by mattwkelly** [comment]
@Otto42 do you know of any other plugins that generate Open Graph Protocol markup?

**Comment by mattwkelly** [comment]
@rgharpuray This should be a top level error message that's displayed both on the Plugin pages and the Facebook setttings page.

See fb_install_warning().

**Comment by mattwkelly** [comment]
Actually, let's only display it on the Facebook settings page for now.  That way, we can avoid adding a Dismiss link for now.

**Comment by Otto42** [comment]
@mattwkelly There's probably a lot of plugins that generate OG markup. My own SFC plugin does, for example. Anything that adds a Like button... Most of the "SEO" plugins... the list is probably at least a couple hundred plugins long.

I'll ping Scott, he has a copy of the plugin repo, might be able to generate a list.

**Comment by mattwkelly** [comment]
That would be awesome, thanks.  Btw, if you have any clever ideas on a better way to solve this, that might be handy.

**Comment by mattwkelly** [comment]
Hit enter too soon-- clever ideas around 1) way to automatically suppress extra OG meta tags or 2) detect extra meta tags.

For #2, we might have an API for this eventually.

**Comment by Otto42** [comment]
1) Only way to suppress I can think of would be to use output buffering around the wp_head action, then filter those to remove any og: markup from it. Have to be careful to leave the rest though. And even then you'll have people complaining about it, because they want to customize their own meta in some way. I frequently have people complain about SFC generating the meta and asking me for an option to turn it off. My response is usually just "no" and be done with it.

2) detection: same problem, same solution. Use output buffering around wp_head and look for it in the string.

**Comment by mattwkelly** [comment]
#1 sounds reasonable.  I'll open an issue.

**Comment by Otto42** [comment]
List of plugin slugs that contain og:title and thus are probably generating metadata (count: 134)

1-click-retweetsharelike
2-click-socialmedia-buttons
add-facebook-og-meta-tags-paulund
add-link-to-facebook
add-meta-tags
aj-wp-facebook-like-and-send
amarinfotech-downlaod-with-fb-connect
another-wordpress-classifieds-plugin
aprils-facebook-like-button
aprils-super-functions-pack
author-hreview
bye-maridjan-seo
cd34-header
comment-juice
contentshare
custom-facebook-and-google-thumbnail
dudelols-easy-facebook-share-thumbnails
dw-fb-sendlike
easy-facebook-share-thumbnails
easy-social-media
easy-toolbox
facebook-awd
facebook-comment-for-wordpress
facebook-comments-for-wordpress
facebook-connect-plugin
facebook-ilike
facebook-image-fix
facebook-like
facebook-like-a-lot
facebook-like-and-comment
facebook-like-and-send-2-in-1
facebook-like-button
facebook-like-button-for-dummies
facebook-like-button-plugin
facebook-like-content-locker
facebook-like-for-marketers
facebook-likes-you
facebook-meta-tags
facebook-open-graph-meta
facebook-open-graph-meta-for-wordpress
facebook-open-graph-meta-in-wordpress
facebook-open-graph-widget
facebook-opengraph
facebook-optimize
facebook-page-publish
facebook-recommend-widget
facebook-revised-open-graph-meta-tag
facebook-send-button
facebook-share-new
facebook-social-plugins
facebook-tools
fanpage-connect
fatpanda-facebook-comments
fb-open-graph-actions-free
fb-thumbnail-config
fbpromotions
fbvirallike
fix-facebook-like
flexo-facebook-manager
flexo-social-gallery
foragr-activity-stream
foxyshop
fp
head-cleaner
head-meta-facebook
hyves-respect
jotlinks-button
jw-player-plugin-for-wordpress
kblog-metadata
kevinjohn-gallagher-pure-web-brilliants-social-graph-control
leenkme
like
like-button-plugin-for-wordpress
like-buttons
me-likey-a-facebook-open-graph-plugin
mediaembedder
meta-ographr
mouseover-share-buttons-by-newsgrape
multilpe-social-media
network-publisher
og-meta
ogp
only-tweet-like-share-and-google-1
open-graph
open-graph-protocol-in-posts-and-pages
open-graph-protocol-tools
opengraph-and-microdata-generator
opengraph-metatags-for-facebook
professional-share
scrolling-social-sharebar
scrolling-twitter-like-google-plusone-linkedin-and-stumbleupon
seo-facebook-comments
seopress
share-buttons
share-center-pro
sharepress
shareyourcart
sharing-is-caring
shopp-facebook-like-button-sflb
shopp-open-graph-helper
shorten2ping
simple-facebook-comments-for-wordpress
simple-facebook-connect
simple-open-graph
slick-social-share-buttons
social-discussions
social-graph-protocol
social-kundi
social-maven
social-networks-auto-poster-facebook-twitter-g
social-sharing-toolkit
socialize
wonderm00ns-simple-facebook-open-graph-tags
woocommerce
wordbooker
wordpress-connect
wordpress-facebook-integrate
wordpress-plugin-seo-and-facebook-opengraph-and-google-schema
wordpress-seo
wordpress-social-ring
wp-facebook-like
wp-facebook-like-send-open-graph-meta
wp-facebook-like-this
wp-facebook-likebutton
wp-facebook-open-graph-protocol
wp-facebook-plugin
wp-facebookconnect
wp-fb-commerce
wp-grow-button
wp-ogp
wp-open-graph-meta
wpmu-dev-facebook-addon
wpstorecart
zoltonorg-social-plugin

**Comment by mattwkelly** [comment]
This is _awesome_, thanks @Otto42 .  @rgharpuray , we should update the list with this.

**Comment by rgharpuray** [comment]
Updated list, and added a warning/redirect for disabling conflicting plugins.

**Comment by mattwkelly** [comment]
Sounds like you're still working on this.  Let me know when it's ready to go and I'll take a look.

**Comment by rgharpuray** [comment]
I think it's ready, it shows the warning on the settings page at the top-- anything missing?

**Comment by Otto42** [comment]
Okay, that code won't work. The PluginURI field isn't always the wordpress.org url of the plugin. Each plugin can set their own URI.

To pick one at random, for example: facebook-revised-open-graph-meta-tag

The Plugin URI for that is: http://thecodep0et.com/facebook-revised-open-graph-meta-tag-plugin/

As you can see in the plugin code itself: http://plugins.svn.wordpress.org/facebook-revised-open-graph-meta-tag/trunk/index.php

If you're only going to base it on the slug (reasonable), then you need to get that from the directory name that the plugin is installed into.

You can call get_plugins() to get a list of all the plugins and their data, but this should be done sparingly, as it's an expensive call to make with all the file operations and such. 

Alternatively, you could also call get_option( 'active_plugins', array() ); to get a list of the active plugins, then check through those to see if you find any matches.

**Comment by rgharpuray** [comment]
Oh that makes sense, I used a script for getting the plugin URI's for the static array. I'll have to go through verifying/correcting each of them. 

I used get_plugins() because when I used "get_option( 'active_plugins', array() );" I only got the plugin name and its local path. get_plugins() gave me a lot of other fields (most importantly PluginURI). Is there any way to get around this? I agree there's no reason to give a warning if they have a plugin but its deactivated.

**Comment by Otto42** [comment]
Well, it depends on how you want to do it. If you are using the PluginURI, then you'll need to read the plugin files, which is a long running operation. Don't do it too often.

If you're only going to check the slug, then that's usually the same as the first part of the plugin path in the active_plugins option. Like "plugin-slug/file.php", You could parse that and just check against the slug.

**Comment by rgharpuray** [comment]
Yeah I think I should opt for the latter. I'll get the active plugins, and access their .php files and get the pluginURI there. I can then check to see if the static array of conflicting plugin URIs contains this parsed pluginURI. But the static array pluginURIs for all 134 still needs to be verified/corrected. Sound correct?

**Comment by Otto42** [comment]
For verifying for the case of plugin upgrades on the API servers, we use plugin name, slug, and URI, on a somewhat sliding scale, to verify matches.

You can use get_plugin_data() to get the info from a plugin. But again, use sparingly. Not every load.

And yeah, you'd still have to build the URI list. Note that not all of them may have a URI defined.

**Comment by rgharpuray** [comment]
The get_plugin_data function doesnt work for me (I tried with all different path strings for the $plugin_file option (absolute, relative, current dir). It returns the fields with all empty strings, even with the files present. Any ideas what might be causing this?

**Comment by Otto42** [comment]
This code works.

```
$plugins = get_option('active_plugins',array());
foreach ($plugins as $plugin) {
    $data = get_plugin_data(WP_PLUGIN_DIR . '/' . $plugin);
    var_dump($data);
}
```

**Comment by rgharpuray** [comment]
This should fix half of the problem (I still need to verify/correct the URI list).

**Comment by mattwkelly** [comment]
"Please disable conflicting plugins, on the plugins page." -> "Potential conflicts with the Facebook plugin have been detected.  Please consider disabling the following plugins."

Then, nix "Consider the following:".

Also, I don't see any utility to listing the plugin's URL, so nix that.  Eg, " : http://akismet.com/?return=true"

I have the Yoast SEO plugin installed, but I don't see any conflicts.  Can you investigate and verify that this is working with a handful of the top plugins (dozen or so?).

**Comment by Otto42** [comment]
I don't think Yoast's SEO plugin conflicts, except that it also has the option to add OpenGraph data.

**Comment by mattwkelly** [comment]
Also, why are we potentially conflicting with Akismet, anyway?  I don't see it in the list that @Otto42 pasted above.

As part of testing that conflicts in the list above show up in the error message, can you test a handful of popular plugins that shouldn't conflict, like Akismet, to make sure that they don't show up in the list?

**Comment by mattwkelly** [comment]
@Otto42 It does generate Open Graph meta data, though, which kills Facebook's scraper.

**Comment by rgharpuray** [comment]
Akismet isn't in fact a conflict, I'm removing that. The first few were for testing.

**Comment by rgharpuray** [comment]
What's the pluginURI in the .php file for SEO yoast?

**Comment by Otto42** [comment]
http://yoast.com/wordpress/seo/#utm_source=wpadmin&utm_medium=plugin&utm_campaign=wpseoplugin

You can see it here: http://plugins.svn.wordpress.org/wordpress-seo/trunk/wp-seo.php

**Comment by mattwkelly** [comment]
This is what I get: "Potential conflicts with the Facebook plugin have been detected. Please consider disabling the following plugins here.
1. Akismet2. WordPress SEO"

Can you just change the list to be comma-delimited?  Thanks

**Comment by mattwkelly** [comment]
Other than that, ready to merge.

**Comment by rgharpuray** [comment]
Done. Wait to merge however, because the list still needs to be verified ( the plugin URIs were naively written as /extend/plugins/\* ) to make sure pluginURIs are correct. Other then that, everything looks good to me

**Comment by mattwkelly** [comment]
I'm confused.  You want me to wait to merge, as you're verifying the list?

**Comment by rgharpuray** [comment]
Yeah the pluginURI list -- working on that now

**Pull request merged**
