### PR TITLE
Comments: FB comments into WP DB

### PR DESCRIPTION
**Pull request by rgharpuray**
Here is the first PR so comments via FB social plugin also show up, when FB comments are disabled. Next one will handle the 3 options and loading comment meta.

### CODE REVIEW

**Comment by colmdoyle** [comment]
@rgharpuray - Might be an idea to squash all these commits. Will make life easier for reviewing.

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by mattwkelly** [comment]
Agreed-- can you squash? Also, can you merge this and https://github.com/facebook/wordpress/pull/221 ?

**Comment by rgharpuray** [comment]
I think that PR can be dropped, since it's already part of this one.

**Comment by rgharpuray** [comment]
The commit called "new branch for fb style comments" (5638b41) has all the changes that need to be reviewed. Ignore the ones after (they are not real changes).

**Comment by mattwkelly** [comment]
Can we close https://github.com/facebook/wordpress/pull/221 then?

**Comment by rgharpuray** [comment]
closed

**Comment by niallkennedy** [comment]
Facebook Comments Box optionally supports third-party login providers (AOL, Yahoo, Hotmail). Sync'd comments with WordPress comments system would need to be able to save author data represented by these third-party login providers (name, email, URL) to properly attribute posts to their author.

**Comment by mclin** [comment]
+1

Would be nice to have the correct number of comments show up in [comments_popup_link](http://codex.wordpress.org/Function_Reference/comments_popup_link)

**Comment by niallkennedy** [comment]
Comments Box provides a JS-focused solution with many filter overrides for current publishers. Closing the WordPress comment form approach.

**Pull request closed without merging**
