### PR TITLE
Mobile Improvements via Mediaquery

### PR DESCRIPTION
**Pull request by rgharpuray**
Fixes 'page' filling out, and comments box alignment.

### CODE REVIEW

**Comment by mattwkelly** [comment]
Looking good. Can we make the comments box stretch to take 100% of the white space available on mobile (without breaking the layout, of course)?

**Comment by rgharpuray** [comment]
For some reason I'm struggling to get the width to change for the comments box.. See the css file (I played around a lot with .fb-comments' width field with no luck!). I assume a parent class is overriding the width field....

**Comment by mattwkelly** [comment]
Once that's figured out, take a look at the original issue.  We should make sure things like wptouch work properly.

**Comment by rgharpuray** [comment]
Sounds good

**Pull request merged**
