### PR TITLE
Default image support added

### PR DESCRIPTION
**Pull request by pedrolamas**
Blog administrator is now allowed to set a default image to be used when
posting articles without a designated thumbnail to Facebook

This will bypass the automatic search for images on the page being shared/liked made by Facebook.

### CODE REVIEW

**Comment by niallkennedy** [comment]
Sites and networks can currently achieve the same result through the `fb_meta_tags` filter.

Open Graph protocol supports specifying multiple images. A site offering a preview image on share could allow a sharer to select an image from a set. Default behavior is the first image specified meeting the minimum requirements of the parser (e.g. JPEG|PNG 200x200 or higher) becomes the image part of the summary.

If you'd like to act on the filter data you can add your own site or network image with or without an existing image present. If another image exists then you're providing an extra option. If no existing image then you've just provided one explicit declaration.

**Comment by pedrolamas** [comment]
I agree, but right now, if you make a post in your Wordpress and set a thumbnail image on it (lower right on the side bar) that is the image that will be used when posting to Facebook!

No other option will be given to you and that is what the current version of the plugin actually does -- I just added an optional fallback! :)

**Comment by niallkennedy** [comment]
Yes, the current behavior is to use [the post thumbnail](http://codex.wordpress.org/Post_Thumbnails). If you want to override that behavior, either adding your own image as an alternate choice or removing the thumbnail and replacing with your own image, you can do that now in your site's plugin or theme code through the `fb_meta_tags` [filter](http://codex.wordpress.org/Plugin_API#Hook_in_your_Filter).

**Comment by pedrolamas** [comment]
Yes, but I'm lazy... I don't like to set the same image over and over again! :D

But I do make a good point: this is more a Wordpress issue than a Facebook plugin issue!

**Pull request closed without merging**
