### PR TITLE
Move css files to <head>

### PR DESCRIPTION
**Pull request by mhui**
Moves css files to head instead of footer

https://github.com/facebook/wordpress/issues/194

### CODE REVIEW

**Comment by ashfame** [comment]
Commit c01fc7653ebf32fce8622e0c79196433f9bc98f0 doesn't have any fix. And Commit 4984964e6abf818961e57d142d7ec533afc8e0f5 actually removes how styles are enqueued in WordPress and just spit them in head. Not good! You are actually degrading it mate.

**Comment by mhui** [comment]
Alright I will fix this

**Comment by ashfame** [comment]
Remember if you are just trying to fix the order of stylesheets being loaded, you could use the dependency argument for registering/enqueueing it. But I believe this should be independent of this need as we won't know what will be the name of main stylesheet of X theme upon which this plugin will be activated.

**Comment by mhui** [comment]
I agree

**Pull request closed without merging**
