### PR TITLE
Replace the FB Comments iframe with xfbml fb:comments-count

### PR DESCRIPTION
**Pull request by colmdoyle**

### CODE REVIEW

**Comment by colmdoyle** [comment]
Can we close this sucker?

cc @mattwkelly

**Comment by mattwkelly** [comment]
Let me give this some thought in context Rishi's recent comments work.

**Comment by niallkennedy** [comment]
I think the XFBML is a good intermediate step until a more server-side comments interface is exposed within WordPress.

Unfortunately there is no HTML5 version, meaning we're mixing HTML5 and XFBML markup methods on the same page.

I added the XFBML version in my current comments file in progress. I changed the text to put "Comments" after the DOM-inserted number to [better match WordPress default](http://core.trac.wordpress.org/browser/tags/3.4.2/wp-includes/comment-template.php#L562).

**Comment by niallkennedy** [comment]
XFBML comments count is built-in to plugin version 1.1 as a [comments_number](http://codex.wordpress.org/Function_Reference/comments_number) response commonly called by template code.

https://github.com/facebook/wordpress/blob/master/social-plugins/class-facebook-comments.php#L45

**Pull request closed without merging**
