### PR TITLE
Update fb-open-graph.php

### PR DESCRIPTION
**Pull request by pixeline**
Fix for plugin not showing the correct post image. (Reverted to meta og:image instead of http://ogp.me/ns#image )

### CODE REVIEW

**Comment by Otto42** [comment]
Err, using og:image would be incorrect without the proper XML namespacing at the top of the document, which the plugin as a whole does not (and cannot) add. http://ogp.me/ns#image is the correct thing to have here.

**Comment by pixeline** [comment]
Well, believe me: as such, it does not work: when commenting an article using the FB Comments with "publish to FB" checkbox ticked, the wrong image is attached. Changing this line of code solves it.
But maybe there is a smarter fix: i'm all ears and can test it against the system where the plugin fails.

**Comment by niallkennedy** [comment]
[Open Graph protocol](http://ogp.me/) markup is based on the [RDFa Core 1.1a](http://www.w3.org/TR/rdfa-syntax/) specification for embedding semantic data in a document. It is possible to shorten a property definition by [defining a CURIE](http://www.w3.org/TR/rdfa-syntax/#s_curieprocessing) in a parent element.

Some consuming agents might choose to assume an observance of an `og` prefix refers to Open Graph protocol if no CURIE mention is present. There's incorrect markup across the web and an XML prefix without a namespace declaration or RDFa data without a prefix CURIE mapping is no different.

The cleanest method is to declare the prefix mapping in a parent element of our meta: head or html. Those elements might be present, and a template including those elements might provide a WordPress plugin with a way to add some code to the plugin (commonly language_attributes when it's used and we make assumptions about where it's used).

Given we can only really control the markup we're generating the plugin outputs a full IRI instead of relying on the ability to add a prefix CURIE on a parent. It's valid RDFa, explicitly declares the property source instead of having a consuming agent assuming a common mapping, and best for the web.

Your milage may vary depending on the parser. If you notice a parser is not properly consuming RDFa with full IRIs you should file a bug against that parser.

**Comment by Otto42** [comment]
If you're actually seeing this on Facebook itself, try using the Facebook Debugger and report what it says:
https://developers.facebook.com/tools/debug

Note that using the debugger has been known to clear out caches on Facebook for the given URL, seemingly making problems with showing the wrong image or description magically disappear for the given URL.

**Comment by pixeline** [comment]
Thanks Nial, correct me if i'm wrong but i looked around the code and it seems to me the parser in this case is Facebook-hosted comment injection system called inside an iframe.

**Pull request closed without merging**
