### PR TITLE
fixed acess token bug

### PR DESCRIPTION
**Pull request by rgharpuray**
I discussed with Matthew, and we think this should do it.

### CODE REVIEW

**Comment by mhui** [comment]
Actually I don't think we need set_transient( 'fb_extended_access_token_' . $facebook->getUser(), 'extended', 60_60_24*7 ); unless we plan on using get_transient later with the key 'fb_extended_access_token_' . $facebook->getUser().

**Comment by rgharpuray** [comment]
done

**Comment by mattwkelly** [comment]
Looks reasonable, but let's keep a close eye on this one.

**Comment by mhui** [comment]
I've been running it on a live site and I got scheduled posts to work for the first time

**Pull request merged**
